baseURL = "https://docs.devops-art-factory.com/"
title = "Terraform & AWS 101"
theme = "hugo-theme-learn"
defaultContentLanguage="ko"
uglyurls = false
relativeURLs = true

[params]
  description = "Documentation for Hugo Learn Theme"
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "mine"
  showVisitedLinks = false
  disableSearch = false
  disableAssetsBusting = false
  disableLanguageSwitchingButton = true
  disableShortcutsTitle=false
  disableInlineCopyToClipBoard = true


## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
hrefTargetBlank = true

[outputs]
home = [ "HTML", "JSON"]
page = [ "HTML" ]
