baseURL = "https://terraform101.inflearn.devopsart.dev/"
title = "Terraform & AWS 101"
theme = "learn"
defaultContentLanguage="ko"
relativeURLs=true
canonifyURLs=false

# Will give values to .Lastmod etc.
enableGitInfo = true

[params]
  description = "Documentation for Hugo Learn Theme"
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "mine"
  showVisitedLinks = false
  disableSearch = false
  disableAssetsBusting = false
  disableLanguageSwitchingButton = true
  disableShortcutsTitle=false
  disableInlineCopyToClipBoard = true


## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
hrefTargetBlank = true
